
build31 : 31q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build32 : 32q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build33 : 33q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build34 : 34q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build35 : 35q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build36 : 36q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build37 : 37q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build38 : 38q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build39 : 39q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build40 : 40q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga


# test

test : answer_34.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga
