
build11 : 11q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build12 : 12q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build13 : 13q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build14 : 14q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build15 : 15q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build16 : 16q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build17 : 17q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build18 : 18q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build19 : 19q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build20 : 20q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

