
build21 : 21q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build22 : 22q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build23 : 23q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build24 : 24q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build25 : 25q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build26 : 26q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build27 : 27q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build28 : 28q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build29 : 29q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build30 : 30q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga


# test

test : answer_28.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga
