
build1 : 1q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge


build2 : 2q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build3 : 3q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build4 : 4q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build5 : 5q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build6 : 6q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build7 : 7q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build8 : 8q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build9_c : 9q_constant.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build9_v : 9q_variable.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

build10 : 10q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o fuga

# test

build_hsv : hsv.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

test : answer_1.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge