
build1 : 1q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge


build2 : 2q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build3 : 3q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge

build4 : 4q.cpp
	g++ $^ -g -Wall `pkg-config --cflags --libs opencv` -o hoge